"""add thumb_url 字段 for posts table

Revision ID: 1783151c2891
Revises: 46708e82d49d
Create Date: 2019-05-19 18:59:12.974237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1783151c2891'
down_revision = '46708e82d49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_url')
    # ### end Alembic commands ###
