"""create posts table

Revision ID: 46708e82d49d
Revises: 07fd75194682
Create Date: 2019-05-14 09:27:40.885438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46708e82d49d'
down_revision = '07fd75194682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
